"""Kuroda fibre tree: the custom static prop in the centre of the Kuroda Plaza court, plus its lights.

build()        textures (Pillow -> vtex), Blender headless (geometry, SMDs, QC), studiomdl. Raises on failure.
pack_pairs()   (internal path, disk path) for every file the BSP must carry.
place(m, ...)  prop_static plus its lights:
               - a down light through the canopy (dappled shadows with vrad -StaticPropPolys)
               - red glow under the Kuroda emblems and cyan at the floor ports
               - warm uplights on the trunk
               - env_sprite glows on a few fibre tips
Sources and rebuild notes: monument/README.md.
"""
from __future__ import annotations

import importlib.util
import json
import math
import re
import subprocess
import sys
from pathlib import Path

import assets
import kit
from vmflib import VMF

SRC = Path(__file__).resolve().parent
DIR = SRC / "monument"
BUILD = SRC / "build" / "monument"
GAME = assets.ROOT / "dystopia"
BLENDER = Path(r"C:\Program Files\Blender Foundation\Blender 5.2\blender.exe")
STUDIOMDL = Path(r"M:\SteamLibrary\steamapps\common\Source SDK Base 2013 Multiplayer\bin\studiomdl.exe")

MODEL = "models/blackice/kuroda_tree.mdl"
MODEL_EXT = (".mdl", ".vvd", ".dx80.vtx", ".dx90.vtx", ".sw.vtx", ".phy")
MATERIALS = ("kuroda_tree_cable.vmt", "kuroda_tree_cable.vtf", "kuroda_tree_cable_n.vtf",
             "kuroda_tree_concrete.vmt", "kuroda_tree_concrete.vtf", "kuroda_tree_concrete_n.vtf",
             "kuroda_tree_neon.vmt", "kuroda_tree_neon.vtf", "kuroda_tree_leaf.vmt", "kuroda_tree_leaf.vtf")
ANCHORS = DIR / "kuroda_tree_lights.json"     # generated by build_tree.py: floor ports, sprite tips, hub
RED, CYAN, WHITE, WARM, CANOPY = (255, 60, 70), (90, 220, 255), (225, 240, 255), (255, 222, 185), (170, 225, 255)
EMBLEM_FACES = (180, 60, 300)                  # planter faces with a Kuroda emblem (180 = west, the approach)


def _textures():
    spec = importlib.util.spec_from_file_location("tree_textures", DIR / "tree_textures.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _run(cmd, log: Path, **kw):
    p = subprocess.run([str(c) for c in cmd], capture_output=True, text=True, encoding="utf-8", errors="replace", **kw)
    log.write_text(p.stdout + p.stderr, encoding="utf-8")
    return p.returncode, p.stdout + p.stderr


def build(previews=False) -> list[Path]:
    """Regenerate everything and compile the model. previews=True also renders build/monument_preview_*.png."""
    _textures().build()
    BUILD.mkdir(parents=True, exist_ok=True)
    qc = DIR / "kuroda_tree.qc"
    code, out = _run([BLENDER, "--background", "--factory-startup", "--python", DIR / "build_tree.py", "--",
                      "--out", BUILD, "--qc", qc] + (["--preview", SRC / "build"] if previews else []),
                     BUILD / "blender.log", timeout=900)
    info = next((json.loads(l[14:]) for l in out.splitlines() if l.startswith("MONUMENT_INFO ")), None)
    if code or info is None:
        raise RuntimeError(f"Blender build failed, see {BUILD / 'blender.log'}\n{out[-1500:]}")
    for ext in MODEL_EXT:                       # never let stale output pass the checks below
        (GAME / (MODEL[:-4] + ext)).unlink(missing_ok=True)
    code, log = _run([STUDIOMDL, "-game", GAME, "-nop4", qc], BUILD / "studiomdl.log", timeout=600, cwd=DIR)
    bad = [l for l in log.splitlines() if re.search(r"(?i)error|warning", l)]
    if code or "Completed" not in log or bad:
        raise RuntimeError(f"studiomdl failed, see {BUILD / 'studiomdl.log'}\n" + "\n".join(bad[:20] or [log[-1500:]]))
    assets.mdl_info.cache_clear()
    mi = assets.mdl_info(MODEL)
    if not mi or not mi["static_ok"]:
        raise RuntimeError(f"{MODEL}: bad header or not a static prop: {mi}")
    files = [d for _, d in pack_pairs()]
    missing = [f for f in files if not f.exists()]
    if missing:
        raise RuntimeError(f"missing outputs: {missing}")
    print(f"monument: {info['tris']} tris, {info['pieces']} collision pieces, materials {info['materials']}, "
          f"hull {mi['hull_min']} .. {mi['hull_max']}")
    return files + [Path(f) for f in info.get("previews", [])]


def pack_pairs() -> list[tuple[str, Path]]:
    """Model + material files the BSP pak must carry."""
    stem = MODEL[:-4]
    pairs = [(stem + ext, GAME / (stem + ext)) for ext in MODEL_EXT]
    return pairs + [(f"materials/models/blackice/{n}", GAME / "materials" / "models" / "blackice" / n) for n in MATERIALS]


def _anchors() -> dict:
    try:
        return json.loads(ANCHORS.read_text(encoding="ascii"))
    except (OSError, ValueError):
        return {"ports": [], "sprites": [], "hub": [1, -1, 306], "top": 380}


def place(m: VMF, x, y, z, yaw=0):
    """Tree with its base centre at (x, y, z) on the floor. At yaw 0 an emblem faces west (the approach)."""
    kit.prop(m, MODEL, x, y, z, yaw=yaw, solid=6, on_floor=False)
    a = math.radians(yaw)

    def rot(px, py, pz):
        return x + px * math.cos(a) - py * math.sin(a), y + px * math.sin(a) + py * math.cos(a), z + pz

    def at(r, az, dz):
        return rot(r * math.cos(math.radians(az)), r * math.sin(math.radians(az)), dz)

    anc = _anchors()
    # canopy light: high above the crown, straight down (kit.spot: pitch < 0 = down). With vrad -StaticPropPolys
    # the fibres, tips and leaves throw a dappled shadow over the court floor.
    kit.spot(m, x, y, z + 640, pitch=-90, color=CANOPY, bright=260, inner=26, outer=48,
             _fifty_percent_distance="560", _zero_percent_distance="1000")
    for f in EMBLEM_FACES:                      # red glow under each Kuroda emblem, washing the wet floor
        kit.light(m, *at(128, f, 20), color=RED, bright=70, fifty=48, hundred=170)
    for px, py, pz in anc["ports"]:             # cyan light from the six floor ports
        kit.light(m, *rot(px, py, pz + 10), color=CYAN, bright=36, fifty=32, hundred=120)
    for az in (212, 148):                       # warm uplights set in the pool, grazing the trunk (pitch > 0 = up)
        kit.spot(m, *at(84, az, 47), pitch=52, yaw=(az + yaw + 180) % 360, color=WARM, bright=110, inner=12, outer=24)
    for s in anc["sprites"]:                    # tip glows for the long-range read (the model's halos are small)
        kit.sprite(m, *rot(*s["pos"]), color=WHITE if s["white"] else CYAN, scale=0.3, alpha=120)
    kit.sprite(m, *rot(*anc["hub"]), color=WHITE, scale=0.25, alpha=100)


if __name__ == "__main__":
    for f in build(previews="--previews" in sys.argv):
        print(f)
